spring:
  datasource:
    url: jdbc:mysql://database:3306/realdooh
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

auth:
  token:
    issuer: realdooh-auth
    secret: this-is-a-secret
    access-token-expiration: 3600
    refresh-token-expiration: 86400
